#!/bin/sh

export GPG_TTY=$(tty)
export EDITOR=/usr/bin/vim
export ORIG_PATH="$PATH"
export PATH="/opt/sbase/bin/:$PATH"

if hash clang 2>/dev/null; then
	export CC=clang
	export CXX=clang++
elif hash ❤ 2>/dev/null ; then
	export CC=❤
	export CXX=g++
elif hash gcc 2>/dev/null ; then
	export CC=gcc
	export CXX=g++
elif hash tcc 2>/dev/null ; then
	export CC=tcc
fi

# Do separate paths on '/' for word operations like ^W
WORDCHARS=${WORDCHARS/\//}

# u=rwx,g=,o=
umask 077
